baseURL = "http://www.robertfpickering.me"
theme = "hugo-theme-robert"
languageCode = "en-gb"
title = "Robert Pickering"

[author]
    name = "Robert Pickering"
    homepage = "http://www.robertfpickering.me"
    about    = "http://www.robertfpickering.me/about"
    twitter  = "robertpi"
    linkedin = "robertpickering"
    github   = "robertpi"
    facebook = "robertfpickering"
    instagram = "robertfpickering"
    email    = "contact@robertfpickering.me"
    mastodon = "https://functional.cafe/@robertpi"

[params]
    [params.sharebutton]
        # If you want to display share buttons set these
        # This is Optional values
        twitter  = false
        facebook = false
        tumblr   = false
        google   = false
        pocket   = false
        # Please set id when you want to display facebook
        facebookAppId = "1772081226418376"

[imaging.exif]
 # Regexp matching the fields you want to Exclude from the (massive) set of Exif info
# available. As we cache this info to disk, this is for performance and
# disk space reasons more than anything.
# If you want it all, put ".*" in this config setting.
# Note that if neither this or ExcludeFields is set, Hugo will return a small
# default set.
includeFields = ".*"

# Regexp matching the Exif fields you want to exclude. This may be easier to use
# than IncludeFields above, depending on what you want.
excludeFields = ""

# Hugo extracts the "photo taken" date/time into .Date by default.
# Set this to true to turn it off.
disableDate = false

# Hugo extracts the "photo taken where" (GPS latitude and longitude) into
# .Long and .Lat. Set this to true to turn it off.
disableLatLong = false